try{
    console.log("Bussiness Logic")
}catch(e){
    console.log("Erroes encountered here")
}